# config.yaml
name: "PSE Energy Status"
version: "1.0.0"
slug: "pse_energy_status"
description: "Monitor PSE energy status markers for home automation"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
url: "https://api.raporty.pse.pl"
auth_api: true
hassio_api: true
homeassistant_api: true
options:
  scan_interval: 300
  SUPERVISOR_TOKEN:
schema:
  scan_interval: int
init: false
map:
  - share:rw
  - ssl
